apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gofiber-backend
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gofiber-backend
subjects:
  - kind: ServiceAccount
    name: gofiber-backend-sa
